name = "hyde-hyde-mateo"
license = "MIT"
licenselink = "https://github.com/stoptime/hyde-hyde-mateo/blob/master/LICENSE.md"
description = "A fork of the hyde-hyde Hugo theme."
tags = ["blog", "theme", "hyde", "highlight.js", "font-awesome", "google analytics", "disqus", "personal", "syntax highlighting", "responsive", "graphcomment"]
features = ["blog", "theme", "highlight.js", "font-awesome", "responsive", "disqus", "graphcomment", "portfolio"]
homepage = "https://github.com/stoptime/hyde-hyde-mateo"
min_version = "0.43"

[author]
    name = "Matt Mayes"
    homepage = "https://www.mattmayes.com"

# If Porting existing theme
[original]
    author =  "htr3n"
    homepage = "https://htr3n.github.io/"
    repo = "https://github.com/htr3n/hyde-hyde"
